services:
  - type: web
    name: cardilla-api
    runtime: node
    rootDir: server
    buildCommand: npm install
    startCommand: npm start
    autoDeploy: true
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: SECRET
        sync: false
      - key: CLIENT_ORIGIN
        sync: false
